//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.OrderContract {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessOrderItem", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class BusinessOrderItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GoodCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OrderItemSumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GoodCount {
            get {
                return this.GoodCountField;
            }
            set {
                if ((this.GoodCountField.Equals(value) != true)) {
                    this.GoodCountField = value;
                    this.RaisePropertyChanged("GoodCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GoodId {
            get {
                return this.GoodIdField;
            }
            set {
                if ((this.GoodIdField.Equals(value) != true)) {
                    this.GoodIdField = value;
                    this.RaisePropertyChanged("GoodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodName {
            get {
                return this.GoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodNameField, value) != true)) {
                    this.GoodNameField = value;
                    this.RaisePropertyChanged("GoodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderItemSum {
            get {
                return this.OrderItemSumField;
            }
            set {
                if ((this.OrderItemSumField.Equals(value) != true)) {
                    this.OrderItemSumField = value;
                    this.RaisePropertyChanged("OrderItemSum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessOrder", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class BusinessOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.OrderContract.BusinessOrderItem[] OrderItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OrderSumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDateField, value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.OrderContract.BusinessOrderItem[] OrderItems {
            get {
                return this.OrderItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderItemsField, value) != true)) {
                    this.OrderItemsField = value;
                    this.RaisePropertyChanged("OrderItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderSum {
            get {
                return this.OrderSumField;
            }
            set {
                if ((this.OrderSumField.Equals(value) != true)) {
                    this.OrderSumField = value;
                    this.RaisePropertyChanged("OrderSum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderContract.IOrderContract", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IOrderContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderContract/AddOrder", ReplyAction="http://tempuri.org/IOrderContract/AddOrderResponse")]
        string AddOrder(Client.OrderContract.BusinessOrderItem[] businessOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderContract/AddOrder", ReplyAction="http://tempuri.org/IOrderContract/AddOrderResponse")]
        System.Threading.Tasks.Task<string> AddOrderAsync(Client.OrderContract.BusinessOrderItem[] businessOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderContract/GetOrders", ReplyAction="http://tempuri.org/IOrderContract/GetOrdersResponse")]
        Client.OrderContract.BusinessOrder[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderContract/GetOrders", ReplyAction="http://tempuri.org/IOrderContract/GetOrdersResponse")]
        System.Threading.Tasks.Task<Client.OrderContract.BusinessOrder[]> GetOrdersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderContractChannel : Client.OrderContract.IOrderContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderContractClient : System.ServiceModel.ClientBase<Client.OrderContract.IOrderContract>, Client.OrderContract.IOrderContract {
        
        public OrderContractClient() {
        }
        
        public OrderContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddOrder(Client.OrderContract.BusinessOrderItem[] businessOrder) {
            return base.Channel.AddOrder(businessOrder);
        }
        
        public System.Threading.Tasks.Task<string> AddOrderAsync(Client.OrderContract.BusinessOrderItem[] businessOrder) {
            return base.Channel.AddOrderAsync(businessOrder);
        }
        
        public Client.OrderContract.BusinessOrder[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<Client.OrderContract.BusinessOrder[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
    }
}
